name: Run tests

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
      source_path:
        required: false
        type: string
        default: './'
      tests_path:
        required: false
        type: string
        default: './tests'

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Install Poetry
        run: pip install poetry

      - name: Set up Python${{ inputs.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
          cache: "poetry"

      - name: Install dependencies
        run: |
          cd ${{ inputs.source_path }}
          poetry install --with dev

      - name: Run tests
        run: |
          cd ${{ inputs.tests_path }}
          poetry run pytest .